version: '3.9'
services:
  homebot:
    build: .
    restart: "always"
    ports:
      - "8080:8080"
    env_file:
      - "env.properties"
    links:
      - speedtest

  speedtest:
    build: ./speedtest
    ports:
      - "8000:8000"
