telegram:
  token: ${TELEGRAM_TOKEN}
  allowed-users: ${TELEGRAM_ALLOWED_USERS}

utorrent:
  base-url: ${UTORRENT_BASE_URL}
  username: ${UTORRENT_USERNAME}
  password: ${UTORRENT_PASSWORD}

fastmile:
  base-url: ${FASTMILE_BASE_URL}
  username: ${FASTMILE_USERNAME}
  password: ${FASTMILE_PASSWORD}

logging.level:
  org.asynchttpclient: ERROR
  io.netty: ERROR
